version: '3.8'
services:
  python-bot:
    build: .
    dockerfile: Dockerfile.python
    env_file: .env
  php-bot:
    build:
      context: .
      dockerfile: Dockerfile.php
    env_file: .env
